### ISSUE TITLE
Minor update in running live_predictions

### ISSUE THREAD

**Issue by aungsanwin** [marcogdepinto/emotion-classification-from-audio-files#14]
Hi Marco,

I was trying out with live_predictions. I have following errors.
numpy.AxisError: axis 2 is out of bounds for array of dimension 2

It comes from 
x = np.expand_dims(mfccs, axis=2)
I print mfccs, it shows (40,) It means i have to change to axis = 1 and it works. Just for your information.

**Comment by marcogdepinto** [comment]
Hi,
I just tried a clean installation making a git clone of the repo, a new virtual environment and installing the packages listed in the requirements.txt (that I slightly modified today to reduce the number of conda-related packages) and I am not reproducing this error.

I think that could be related to your Python version or to the version of some of the packages you have installed on your machine. For my test, I used Python 3.6 and the exact version of each package as listed in the requirements.txt. Full log below, closing this issue.

/Users/marcogdepinto/PycharmProjects/emotion-classification-from-audio-files/venv/bin/python /Users/marcogdepinto/PycharmProjects/emotion-classification-from-audio-files/live_predictions.py
Using TensorFlow backend.
/Users/marcogdepinto/PycharmProjects/emotion-classification-from-audio-files/venv/lib/python3.6/site-packages/librosa/util/decorators.py:9: NumbaDeprecationWarning: An import was requested from a module that has moved location.
Import of 'jit' requested from: 'numba.decorators', please update to use 'numba.core.decorators' or pin to Numba version 0.48.0. This alias will not be present in Numba version 0.50.0.
from numba.decorators import jit as optional_jit
2020-06-24 21:58:38.193417: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/marcogdepinto/PycharmProjects/emotion-classification-from-audio-files/venv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Model: "sequential_1"

Layer (type) Output Shape Param #
conv1d_1 (Conv1D) (None, 40, 64) 384

activation_1 (Activation) (None, 40, 64) 0

dropout_1 (Dropout) (None, 40, 64) 0

flatten_1 (Flatten) (None, 2560) 0

dense_1 (Dense) (None, 8) 20488

activation_2 (Activation) (None, 8) 0
Total params: 20,872
Trainable params: 20,872
Non-trainable params: 0

Prediction is calm
Prediction is disgust

Process finished with exit code 0
