### ISSUE TITLE
Wrong predictions?

### ISSUE THREAD

**Issue by arianaa30** [marcogdepinto/emotion-classification-from-audio-files#20]
Hi,
Very nice work. I was trying to test the model on two of the samples from TESS dataset itself, but I get wrong predictions. h04.wav which is happy is said to be sad, and output10.wav which is angry said to be happy.

Is the encoding correct in the `live_prediction.py`? Can you test these two files yourself?
[test.zip](https://github.com/marcogdepinto/emotion-classification-from-audio-files/files/5468513/test.zip)

**Comment by marcogdepinto** [comment]
Hi,
the fact that you picked two random samples and the model is not working for me could be an expected behavior - the model is not 100% accurate hence hence you will have files with wrong predictions.
Try testing more files and you will find some correct predictions.
