### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by VKasaraba** [marcogdepinto/emotion-classification-from-audio-files#21]
Hi @marcogdepinto ! I really like the idea and implementation of the project. Thank you for the effort!
I need some help tho to get started. I ran the live_predictions.py file and got the following output

![photo_2020-11-11_01-09-56](https://user-images.githubusercontent.com/57074670/98744672-c6bb8780-23ba-11eb-81ca-4f5273eba911.jpg)

I didn't find any documentation on how to understand the table in the output. 
How do I get an emotional level output for my voice file? How to understand the results?
Thank you!!

**Comment by marcogdepinto** [comment]
Hi,
the output is at the end of your picture:

Prediction is calm
Prediction is disgust.
