### ISSUE TITLE
Model not training

### ISSUE THREAD

**Issue by Baibhav-nag** [marcogdepinto/emotion-classification-from-audio-files#30]
This error is coming up during training...please help

![2021-03-25 (1)](https://user-images.githubusercontent.com/74949243/112510053-14a7b980-8db7-11eb-8b62-8eeecd36b529.png)

**Comment by marcogdepinto** [comment]
Most likely due to usage of libraries different from the ones this system is designed to work. Please create a virtual enviroment and use the provided pip file to install the same libraries and versions.
